# Generated by Django 3.1.5 on 2021-01-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending1', 'Pending'), ('Out for delivery1', 'Out for delivery'), ('Delivered1', 'Delivered')], max_length=200, null=True),
        ),
    ]
