# Generated by Django 3.1.5 on 2021-01-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0005_auto_20210121_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='crmapp.Tag'),
        ),
    ]
